nqswap:
  loader: jsonl_template
  path: data/nqswap.jsonl
  fields:
    question: question
    context: context
    answer_context: answer_context
    answer_param: answer_param
  templates:
    context: "Context: {context}\nQuestion: {question}\nAnswer:"
    param: "Question: {question}\nAnswer:"
  targets:
    context: answer_context
    param: answer_param

macnoise:
  loader: jsonl_template
  path: data/macnoise.jsonl
  fields:
    question: question
    context: context
    answer_context: answer_context
    answer_param: answer_param
  templates:
    context: "Context: {context}\nQuestion: {question}\nAnswer:"
    param: "Question: {question}\nAnswer:"
  targets:
    context: answer_context
    param: answer_param

nq_swap_hf:
  loader: nq_swap
  split: dev
  cache_dir: data/hf
  split_ratios:
    train: 0.6
    eval: 0.2
    test: 0.2
  answer_policy: list

nq_swap_openbook:
  loader: nq_swap
  split: dev
  cache_dir: data/hf
  split_ratios:
    train: 0.6
    eval: 0.2
    test: 0.2
  k_shot: 4
  demonstrations_org_context: true
  demonstrations_org_answer: true
  test_example_org_context: false
  answer_policy: list

nq_swap_openbook_sae:
  loader: nq_swap
  split: dev
  cache_dir: data/hf
  split_policy: shared
  shuffle_splits: false
  k_shot: 4
  demonstrations_org_context: true
  demonstrations_org_answer: true
  test_example_org_context: false
  answer_policy: list

nq_swap_openbook_noconflict:
  loader: nq_swap
  split: dev
  cache_dir: data/hf
  split_ratios:
    train: 0.6
    eval: 0.2
    test: 0.2
  k_shot: 4
  demonstrations_org_context: true
  demonstrations_org_answer: true
  test_example_org_context: true
  answer_policy: list

nq_swap_closebook:
  loader: nq_swap
  split: dev
  cache_dir: data/hf
  split_ratios:
    train: 0.6
    eval: 0.2
    test: 0.2
  k_shot: 32
  demonstrations_org_context: true
  demonstrations_org_answer: true
  answer_policy: list

nq_swap_closebook_sae:
  loader: nq_swap
  split: dev
  cache_dir: data/hf
  split_policy: shared
  shuffle_splits: false
  k_shot: 32
  demonstrations_org_context: true
  demonstrations_org_answer: true
  answer_policy: list
