llama2_7b:
  type: hf
  hf_id: meta-llama/Llama-2-7b-hf
  dtype: bfloat16
  device_map: auto
  trust_remote_code: false
  hook_module: model.layers.{layer}

llama3_8b:
  type: hf
  hf_id: meta-llama/Meta-Llama-3-8B
  dtype: bfloat16
  device_map: auto
  trust_remote_code: false
  hook_module: model.layers.{layer}

gemma2_9b:
  type: hf
  hf_id: google/gemma-2-9b
  dtype: bfloat16
  device_map: auto
  trust_remote_code: false
  hook_module: model.layers.{layer}

mistral_7b_v01:
  type: hf
  hf_id: mistralai/Mistral-7B-v0.1
  dtype: bfloat16
  device_map: auto
  trust_remote_code: false
  hook_module: model.layers.{layer}

gpt2:
  type: hf
  hf_id: gpt2
  dtype: float32
  device_map: auto
  trust_remote_code: false
  hook_module: transformer.h.{layer}

tiny_gpt2:
  type: hf
  hf_id: sshleifer/tiny-gpt2
  dtype: float32
  device_map: auto
  trust_remote_code: false
  hook_module: transformer.h.{layer}
